"""
Django settings for apps project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from datetime import timedelta
from os.path import dirname, join, abspath

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# 根目录
ROOT_DIR = os.getcwd()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'i25!3j*7@6nbq65t2ii7nroj)1)ddqtq5i_0-9#$*em%u9u-y('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 可访问白名单
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # DRF
    'rest_framework',
    'message',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'message.middleware.middleware.ResponseMiddleware'
]


ROOT_URLCONF = 'apps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'apps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'codedog_user_db',
        'HOST': '127.0.0.1',  # 数据库地址
        'PORT': 3306,  # 端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'yoki',  # 数据库密码
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# 更改时区为北京时间
TIME_ZONE = 'Asia/Shanghai'
# TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# drf框架的配置信息
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        # 'rest_framework.permissions.IsAuthenticated',
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
    # 用户登陆认证方式
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework_simplejwt.authentication.JWTTokenUserAuthentication',
        # 'message.lib.JWTAuthentication.Authentication',
    ),
    # 全局配置异常模块
    'EXCEPTION_HANDLER': 'message.lib.exception.custom_exception_handler',
    # 修改默认返回JSON的renderer的类
    'DEFAULT_RENDERER_CLASSES': (
        'message.lib.rendererresponse.customrenderer',
    ),
    # 分页
    'DEFAULT_PAGINATION_CLASS': 'message.lib.LimitOffsetPagination.CustomPagination',
    # 'PAGE_SIZE': 10,
}

# 认证后端
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'default': {
            'format': '-%(asctime)s-%(levelname)s-%(name)s: %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'default',
            'filename': join(ROOT_DIR, 'log', 'codedog.log'),
            'maxBytes': 1 << 28,
            'backupCount': 5
        },
        'info_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'formatter': 'default',
            'filename': join(ROOT_DIR, 'log', 'codedog_info.log'),
            'maxBytes': 1 << 28,
            'backupCount': 5
        },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        }
    },
    'loggers': {
        '': {
            'handlers': [
                'file',
                'info_file',
                'console'
            ],
            'level': 'DEBUG',
            'propagate': True,
        },
    }
}

# 公钥

pub_key = '''-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCzC+Uryq+QljDgWvz7IxDXj/p+
DafhR343QQjeJUD6l3UExYztnQbIGltkjPTGJznLYyhc+Y5Bh3N4l6WoVEGi693b
nMyJsXWB3E3cqqlSiCpPYQL92lGGEDna3OVI1r1KxIRrrVMUOXIqA1aTvdu6KXjV
ZaPx+/45JhVGcw9IxQIDAQAB
-----END PUBLIC KEY-----'''

# 密钥

private_key = '''-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQCzC+Uryq+QljDgWvz7IxDXj/p+DafhR343QQjeJUD6l3UExYzt
nQbIGltkjPTGJznLYyhc+Y5Bh3N4l6WoVEGi693bnMyJsXWB3E3cqqlSiCpPYQL9
2lGGEDna3OVI1r1KxIRrrVMUOXIqA1aTvdu6KXjVZaPx+/45JhVGcw9IxQIDAQAB
AoGAbeTyL3PDWIpmy33tYrN+JeDwTahSD3rTJFTdfYP+IxENOPWL71f/Dpjm2YuO
vYTb+1MMNizSPLRHko/5lJzKf49AWVFpDsfpx3tOsOpeZe/oWuUVlX+XI7gSqRNo
aBulb8DJSKByxfN2/pcNYNy7VyWAG1yB2HwCTxJ08V6BGq0CQQDbxvtx2A5JdciE
l7LSotRpGn/1lFz2LB8vsk7qKodh+ugpatfDiap4tjbcUwJKCV0qPHeC45l8TyyX
qvfpTKSDAkEA0I5dxE+PFaSA3bv0FcZ0QT+WaadKp7hmdKdixXbYrB/Y6Ji4G6+Y
7D1+JxJIYmOOkz10tdGa/82G1Uy1P0OrFwJAOoxo4ewv6iwBjiknj2uncJSJsC+l
EEOyzy8OTN2lkVmZTadT8ZiUHHJWbR2EB5s1AZJ4OBtQAUjKVWFLiBBN5wJBAIfD
1eigvg2hvD4cR8YRHccIBPucau4KDbBs8tCHEH/kb4jjOh7TzeIkGcaHkVVzZ/IT
9LET1Som+lpKiEa531sCQG7X/5Ij2RW5+3hNQJbBtM7oYoO91I4LCHc5UkWXNB2e
4P/XQQkv0VSbCLCHVs51At/AYJDF2i1AnBH53W26zpQ=
-----END RSA PRIVATE KEY-----'''

SIMPLE_JWT = {
    # minutes=5
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'RS256',
    'VERIFYING_KEY': pub_key,
    'SIGNING_KEY': private_key,

    # 前缀
    'AUTH_HEADER_TYPES': ('Msg',),
    # 'USER_ID_FIELD': 'uid',
    'USER_ID_FIELD': 'id',
    # 生成的令牌中的声明将用于存储用户标识符。
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    # 'TOKEN_USER_CLASS': 'login.models.UserInfo',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',

    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=60),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}
